In [ ]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.2.1-py3-none-any.whl.metadata (17 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.15.2-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.40)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.11/dist-packages (from alembic>=1.5.0->optuna) (4.13.1)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.1.1)
Downloading optuna-4.2.1-py3-none-any.whl (383 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.6/383.6 kB 7.9 MB/s eta 0:00:00
Downloading alembic-1.15.2-py3-none-any.whl (231 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.9/231.9 kB 15.0 MB/s eta 0:00:00
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.15.2 colorlog-6.9.0 optuna-4.2.1

This code loads the Pima Indians Diabetes dataset from a GitHub URL into a Pandas DataFrame and assigns appropriate column names. It prepares the data for further processing or modeling.

In [ ]:
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']
df=pd.read_csv(url, names=columns)
df.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

This code segment replaces zeros in selected medical columns with NaN and fills the missing values with the column-wise mean to clean the dataset.

In [ ]:
col_with_missing_vols=['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[col_with_missing_vols]=df[col_with_missing_vols].replace(0, np.nan)
df.fillna(df.mean(), inplace=True)
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

This code segment splits the dataset into training and testing sets, then standardizes the features using StandardScaler to normalize the data before model training.

In [29]:
X = df.drop('Outcome', axis=1)
y = df['Outcome']
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.3, random_state=42)
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)
print(f'Training dataset shape: {x_train.shape}')
print(f'Testing dataset shape:{ x_test.shape}')

Training dataset shape: (537, 8)
Testing dataset shape:(231, 8)

This code segment defines an Optuna objective function to optimize a RandomForestClassifier by tuning n_estimators and max_depth using 5-fold cross-validation, with accuracy as the scoring metric.

In [30]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
def objective(trial):
  n_estimators=trial.suggest_int('n_estimators', 50, 200)
  max_depth=trial.suggest_int('max_depth', 3, 20)
  model=RandomForestClassifier(
      n_estimators=n_estimators,
      max_depth=max_depth,
      random_state=42
  )
  score=cross_val_score(model, x_train, y_train, cv=5, scoring='accuracy').mean()
  return score

This code segment creates and runs an Optuna study named 'akmal' to maximize the accuracy of a RandomForestClassifier. It uses the TPE sampler for smarter hyperparameter search over 50 trials.

In [36]:
from os import name
study= optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(), study_name='akmal')
study.optimize(objective, n_trials=50)

[I 2025-04-13 04:42:11,734] A new study created in memory with name: akmal
[I 2025-04-13 04:42:12,799] Trial 0 finished with value: 0.7541363793700242 and parameters: {'n_estimators': 126, 'max_depth': 4}. Best is trial 0 with value: 0.7541363793700242.
[I 2025-04-13 04:42:14,029] Trial 1 finished with value: 0.7559709241952233 and parameters: {'n_estimators': 134, 'max_depth': 8}. Best is trial 1 with value: 0.7559709241952233.
[I 2025-04-13 04:42:15,665] Trial 2 finished with value: 0.7503980616130148 and parameters: {'n_estimators': 195, 'max_depth': 4}. Best is trial 1 with value: 0.7559709241952233.
[I 2025-04-13 04:42:16,385] Trial 3 finished with value: 0.755988231221876 and parameters: {'n_estimators': 50, 'max_depth': 8}. Best is trial 3 with value: 0.755988231221876.
[I 2025-04-13 04:42:18,817] Trial 4 finished with value: 0.7708722741433022 and parameters: {'n_estimators': 172, 'max_depth': 16}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:20,012] Trial 5 finished with value: 0.7597092419522327 and parameters: {'n_estimators': 127, 'max_depth': 20}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:21,523] Trial 6 finished with value: 0.7559016960886119 and parameters: {'n_estimators': 160, 'max_depth': 12}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:22,918] Trial 7 finished with value: 0.7634302526825891 and parameters: {'n_estimators': 154, 'max_depth': 7}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:24,531] Trial 8 finished with value: 0.7634129456559363 and parameters: {'n_estimators': 181, 'max_depth': 6}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:25,146] Trial 9 finished with value: 0.7541709934233298 and parameters: {'n_estimators': 72, 'max_depth': 4}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:26,502] Trial 10 finished with value: 0.7559709241952233 and parameters: {'n_estimators': 85, 'max_depth': 17}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:28,057] Trial 11 finished with value: 0.7577881619937694 and parameters: {'n_estimators': 161, 'max_depth': 14}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:30,202] Trial 12 finished with value: 0.7652474904811353 and parameters: {'n_estimators': 159, 'max_depth': 15}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:32,268] Trial 13 finished with value: 0.7690031152647976 and parameters: {'n_estimators': 180, 'max_depth': 16}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:34,110] Trial 14 finished with value: 0.7671685704395984 and parameters: {'n_estimators': 196, 'max_depth': 19}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:35,792] Trial 15 finished with value: 0.7690204222914503 and parameters: {'n_estimators': 179, 'max_depth': 17}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:36,797] Trial 16 finished with value: 0.7615264797507788 and parameters: {'n_estimators': 105, 'max_depth': 13}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:38,168] Trial 17 finished with value: 0.7634129456559363 and parameters: {'n_estimators': 143, 'max_depth': 18}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:39,807] Trial 18 finished with value: 0.7633956386292835 and parameters: {'n_estimators': 177, 'max_depth': 10}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:40,755] Trial 19 finished with value: 0.7652647975077882 and parameters: {'n_estimators': 99, 'max_depth': 11}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:43,541] Trial 20 finished with value: 0.7671512634129456 and parameters: {'n_estimators': 200, 'max_depth': 16}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:45,368] Trial 21 finished with value: 0.7671512634129456 and parameters: {'n_estimators': 178, 'max_depth': 16}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:47,064] Trial 22 finished with value: 0.7671512634129456 and parameters: {'n_estimators': 175, 'max_depth': 18}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:48,816] Trial 23 finished with value: 0.765282104534441 and parameters: {'n_estimators': 184, 'max_depth': 14}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:50,182] Trial 24 finished with value: 0.7634302526825891 and parameters: {'n_estimators': 144, 'max_depth': 20}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:51,812] Trial 25 finished with value: 0.7690031152647976 and parameters: {'n_estimators': 171, 'max_depth': 16}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:53,624] Trial 26 finished with value: 0.7671685704395984 and parameters: {'n_estimators': 191, 'max_depth': 18}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:55,715] Trial 27 finished with value: 0.757822776047075 and parameters: {'n_estimators': 145, 'max_depth': 14}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:57,621] Trial 28 finished with value: 0.7671512634129456 and parameters: {'n_estimators': 167, 'max_depth': 17}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:42:59,801] Trial 29 finished with value: 0.7559190031152648 and parameters: {'n_estimators': 187, 'max_depth': 12}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:43:00,931] Trial 30 finished with value: 0.7596919349255797 and parameters: {'n_estimators': 115, 'max_depth': 15}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:43:02,547] Trial 31 finished with value: 0.7690031152647976 and parameters: {'n_estimators': 169, 'max_depth': 16}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:43:04,156] Trial 32 finished with value: 0.7671512634129456 and parameters: {'n_estimators': 170, 'max_depth': 17}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:43:05,444] Trial 33 finished with value: 0.7597092419522327 and parameters: {'n_estimators': 135, 'max_depth': 19}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:43:07,132] Trial 34 finished with value: 0.7633783316026307 and parameters: {'n_estimators': 151, 'max_depth': 15}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:43:09,630] Trial 35 finished with value: 0.7652474904811353 and parameters: {'n_estimators': 188, 'max_depth': 10}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:43:11,213] Trial 36 finished with value: 0.7671339563862929 and parameters: {'n_estimators': 167, 'max_depth': 13}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:43:12,469] Trial 37 finished with value: 0.7634475597092419 and parameters: {'n_estimators': 132, 'max_depth': 19}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:43:13,911] Trial 38 finished with value: 0.7689858082381447 and parameters: {'n_estimators': 152, 'max_depth': 16}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:43:15,724] Trial 39 finished with value: 0.7671685704395984 and parameters: {'n_estimators': 192, 'max_depth': 20}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:43:16,229] Trial 40 finished with value: 0.7521806853582553 and parameters: {'n_estimators': 51, 'max_depth': 13}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:43:17,894] Trial 41 finished with value: 0.7690031152647976 and parameters: {'n_estimators': 173, 'max_depth': 16}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:43:19,663] Trial 42 finished with value: 0.7634129456559363 and parameters: {'n_estimators': 165, 'max_depth': 17}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:43:22,177] Trial 43 finished with value: 0.7652994115610937 and parameters: {'n_estimators': 182, 'max_depth': 15}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:43:23,659] Trial 44 finished with value: 0.7652647975077882 and parameters: {'n_estimators': 154, 'max_depth': 18}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:43:25,220] Trial 45 finished with value: 0.765282104534441 and parameters: {'n_estimators': 161, 'max_depth': 17}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:43:26,842] Trial 46 finished with value: 0.7504153686396677 and parameters: {'n_estimators': 200, 'max_depth': 3}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:43:28,573] Trial 47 finished with value: 0.765282104534441 and parameters: {'n_estimators': 183, 'max_depth': 14}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:43:30,227] Trial 48 finished with value: 0.7708722741433022 and parameters: {'n_estimators': 172, 'max_depth': 16}. Best is trial 4 with value: 0.7708722741433022.
[I 2025-04-13 04:43:31,689] Trial 49 finished with value: 0.7615610938040844 and parameters: {'n_estimators': 158, 'max_depth': 8}. Best is trial 4 with value: 0.7708722741433022.

This code segment prints the best accuracy score achieved during the Optuna optimization and the corresponding hyperparameters of the best trial.

In [37]:
print(f'best trial accuracy: {study.best_trial.value}')
print(f'best trial paramteres: {study.best_trial.params}')

best trial accuracy: 0.7708722741433022
best trial paramteres: {'n_estimators': 172, 'max_depth': 16}

This code segment generates and displays a plot of the optimization history of the Optuna study, illustrating the progress of the objective function (e.g., accuracy) across all trials.

In [49]:
plot_optimization_history(study).show()

The code segment generates a parallel coordinate plot to visualize how the hyperparameters in the Optuna study affect the objective function's performance.

In [52]:
plot_parallel_coordinate(study).show()

The code plot_slice(study).show() generates a slice plot to visualize how changing one hyperparameter affects the objective function's performance, while keeping other hyperparameters fixed.

In [55]:
plot_slice(study).show()

The code segement generates a contour plot to visualize the relationship between two hyperparameters and the objective function's performance, helping to identify regions of optimal values for both hyperparameters.

In [56]:
plot_contour(study).show()

The code segment generates a parametric importance plot that visualizes the impact of each hyperparameter on the objective function, helping to identify which hyperparameters are most influential in the optimization process.

In [58]:
plot_param_importances(study).show()

This code trains a RandomForestClassifier using the best hyperparameters from the Optuna study, evaluates its performance on the test set, and prints the test accuracy. The accuracy is calculated by comparing predicted labels with actual labels.

In [41]:
from sklearn.metrics import accuracy_score
best_model=RandomForestClassifier(**study.best_trial.params, random_state=42)
best_model.fit(x_train, y_train)
y_pred=best_model.predict(x_test)
test_accuracy=accuracy_score(y_test, y_pred)
print(f'test accuracy with best hyperparameters:{test_accuracy:.2f}')

test accuracy with best hyperparameters:0.74

This code defines an Optuna objective function for optimizing a RandomForestClassifier. It tunes the n_estimators and max_depth hyperparameters and evaluates the model's performance using 5-fold cross-validation, returning the mean accuracy score.

In [42]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
def objective(trial):
  n_estimators=trial.suggest_int('n_estimators', 50, 200)
  max_depth=trial.suggest_int('max_depth', 3, 20)
  model=RandomForestClassifier(
      n_estimators=n_estimators,
      max_depth=max_depth,
      random_state=42
  )
  score=cross_val_score(model, x_train,y_train, cv=5, scoring='accuracy').mean()
  return score

This code creates an Optuna study to maximize the accuracy of a RandomForestClassifier by optimizing hyperparameters using the RandomSampler. It runs the optimization process for 50 trials to find the best-performing hyperparameter configuration.

In [43]:
study=optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())
study.optimize(objective, n_trials=50)

[I 2025-04-13 05:06:06,760] A new study created in memory with name: no-name-44c922c0-ec72-4dfe-87d5-5528574106c4
[I 2025-04-13 05:06:10,084] Trial 0 finished with value: 0.7671339563862929 and parameters: {'n_estimators': 165, 'max_depth': 7}. Best is trial 0 with value: 0.7671339563862929.
[I 2025-04-13 05:06:12,018] Trial 1 finished with value: 0.7615610938040843 and parameters: {'n_estimators': 72, 'max_depth': 14}. Best is trial 0 with value: 0.7671339563862929.
[I 2025-04-13 05:06:14,295] Trial 2 finished with value: 0.7689685012114919 and parameters: {'n_estimators': 166, 'max_depth': 11}. Best is trial 2 with value: 0.7689685012114919.
[I 2025-04-13 05:06:14,862] Trial 3 finished with value: 0.757840083073728 and parameters: {'n_estimators': 62, 'max_depth': 5}. Best is trial 2 with value: 0.7689685012114919.
[I 2025-04-13 05:06:16,193] Trial 4 finished with value: 0.7634302526825891 and parameters: {'n_estimators': 149, 'max_depth': 7}. Best is trial 2 with value: 0.7689685012114919.
[I 2025-04-13 05:06:17,256] Trial 5 finished with value: 0.754153686396677 and parameters: {'n_estimators': 127, 'max_depth': 4}. Best is trial 2 with value: 0.7689685012114919.
[I 2025-04-13 05:06:17,766] Trial 6 finished with value: 0.7559363101419176 and parameters: {'n_estimators': 52, 'max_depth': 12}. Best is trial 2 with value: 0.7689685012114919.
[I 2025-04-13 05:06:18,995] Trial 7 finished with value: 0.7633610245759778 and parameters: {'n_estimators': 129, 'max_depth': 13}. Best is trial 2 with value: 0.7689685012114919.
[I 2025-04-13 05:06:19,586] Trial 8 finished with value: 0.7690031152647976 and parameters: {'n_estimators': 58, 'max_depth': 19}. Best is trial 8 with value: 0.7690031152647976.
[I 2025-04-13 05:06:21,270] Trial 9 finished with value: 0.7708722741433022 and parameters: {'n_estimators': 172, 'max_depth': 16}. Best is trial 9 with value: 0.7708722741433022.
[I 2025-04-13 05:06:23,628] Trial 10 finished with value: 0.765282104534441 and parameters: {'n_estimators': 161, 'max_depth': 17}. Best is trial 9 with value: 0.7708722741433022.
[I 2025-04-13 05:06:24,772] Trial 11 finished with value: 0.7634129456559362 and parameters: {'n_estimators': 102, 'max_depth': 15}. Best is trial 9 with value: 0.7708722741433022.
[I 2025-04-13 05:06:25,735] Trial 12 finished with value: 0.7597092419522324 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 9 with value: 0.7708722741433022.
[I 2025-04-13 05:06:26,486] Trial 13 finished with value: 0.7578920041536863 and parameters: {'n_estimators': 77, 'max_depth': 15}. Best is trial 9 with value: 0.7708722741433022.
[I 2025-04-13 05:06:27,237] Trial 14 finished with value: 0.7541190723433713 and parameters: {'n_estimators': 78, 'max_depth': 12}. Best is trial 9 with value: 0.7708722741433022.
[I 2025-04-13 05:06:27,768] Trial 15 finished with value: 0.7671685704395984 and parameters: {'n_estimators': 54, 'max_depth': 20}. Best is trial 9 with value: 0.7708722741433022.
[I 2025-04-13 05:06:28,525] Trial 16 finished with value: 0.7523018345448251 and parameters: {'n_estimators': 88, 'max_depth': 4}. Best is trial 9 with value: 0.7708722741433022.
[I 2025-04-13 05:06:29,820] Trial 17 finished with value: 0.7522672204915196 and parameters: {'n_estimators': 154, 'max_depth': 4}. Best is trial 9 with value: 0.7708722741433022.
[I 2025-04-13 05:06:31,102] Trial 18 finished with value: 0.7615437867774316 and parameters: {'n_estimators': 136, 'max_depth': 20}. Best is trial 9 with value: 0.7708722741433022.
[I 2025-04-13 05:06:32,751] Trial 19 finished with value: 0.7690031152647976 and parameters: {'n_estimators': 175, 'max_depth': 16}. Best is trial 9 with value: 0.7708722741433022.
[I 2025-04-13 05:06:34,499] Trial 20 finished with value: 0.7634129456559362 and parameters: {'n_estimators': 165, 'max_depth': 15}. Best is trial 9 with value: 0.7708722741433022.
[I 2025-04-13 05:06:36,980] Trial 21 finished with value: 0.7652647975077882 and parameters: {'n_estimators': 177, 'max_depth': 13}. Best is trial 9 with value: 0.7708722741433022.
[I 2025-04-13 05:06:37,844] Trial 22 finished with value: 0.7578573901003808 and parameters: {'n_estimators': 92, 'max_depth': 3}. Best is trial 9 with value: 0.7708722741433022.
[I 2025-04-13 05:06:39,188] Trial 23 finished with value: 0.7541017653167186 and parameters: {'n_estimators': 98, 'max_depth': 3}. Best is trial 9 with value: 0.7708722741433022.
[I 2025-04-13 05:06:40,528] Trial 24 finished with value: 0.750398061613015 and parameters: {'n_estimators': 83, 'max_depth': 16}. Best is trial 9 with value: 0.7708722741433022.
[I 2025-04-13 05:06:42,541] Trial 25 finished with value: 0.7633610245759779 and parameters: {'n_estimators': 152, 'max_depth': 11}. Best is trial 9 with value: 0.7708722741433022.
[I 2025-04-13 05:06:43,605] Trial 26 finished with value: 0.7597092419522327 and parameters: {'n_estimators': 112, 'max_depth': 19}. Best is trial 9 with value: 0.7708722741433022.
[I 2025-04-13 05:06:44,857] Trial 27 finished with value: 0.7596573208722741 and parameters: {'n_estimators': 130, 'max_depth': 15}. Best is trial 9 with value: 0.7708722741433022.
[I 2025-04-13 05:06:45,750] Trial 28 finished with value: 0.7522326064382139 and parameters: {'n_estimators': 110, 'max_depth': 3}. Best is trial 9 with value: 0.7708722741433022.
[I 2025-04-13 05:06:47,879] Trial 29 finished with value: 0.770889581169955 and parameters: {'n_estimators': 177, 'max_depth': 9}. Best is trial 29 with value: 0.770889581169955.
[I 2025-04-13 05:06:49,725] Trial 30 finished with value: 0.7503980616130148 and parameters: {'n_estimators': 155, 'max_depth': 4}. Best is trial 29 with value: 0.770889581169955.
[I 2025-04-13 05:06:50,822] Trial 31 finished with value: 0.7634129456559362 and parameters: {'n_estimators': 114, 'max_depth': 17}. Best is trial 29 with value: 0.770889581169955.
[I 2025-04-13 05:06:52,318] Trial 32 finished with value: 0.7577535479404638 and parameters: {'n_estimators': 158, 'max_depth': 12}. Best is trial 29 with value: 0.770889581169955.
[I 2025-04-13 05:06:53,909] Trial 33 finished with value: 0.7633783316026307 and parameters: {'n_estimators': 169, 'max_depth': 11}. Best is trial 29 with value: 0.770889581169955.
[I 2025-04-13 05:06:54,683] Trial 34 finished with value: 0.7559363101419175 and parameters: {'n_estimators': 79, 'max_depth': 13}. Best is trial 29 with value: 0.770889581169955.
[I 2025-04-13 05:06:56,189] Trial 35 finished with value: 0.765282104534441 and parameters: {'n_estimators': 157, 'max_depth': 19}. Best is trial 29 with value: 0.770889581169955.
[I 2025-04-13 05:06:56,970] Trial 36 finished with value: 0.7578227760470752 and parameters: {'n_estimators': 81, 'max_depth': 14}. Best is trial 29 with value: 0.770889581169955.
[I 2025-04-13 05:06:58,371] Trial 37 finished with value: 0.7652647975077882 and parameters: {'n_estimators': 148, 'max_depth': 18}. Best is trial 29 with value: 0.770889581169955.
[I 2025-04-13 05:07:00,310] Trial 38 finished with value: 0.7690204222914503 and parameters: {'n_estimators': 167, 'max_depth': 9}. Best is trial 29 with value: 0.770889581169955.
[I 2025-04-13 05:07:01,475] Trial 39 finished with value: 0.757822776047075 and parameters: {'n_estimators': 76, 'max_depth': 10}. Best is trial 29 with value: 0.770889581169955.
[I 2025-04-13 05:07:02,567] Trial 40 finished with value: 0.7652647975077881 and parameters: {'n_estimators': 74, 'max_depth': 16}. Best is trial 29 with value: 0.770889581169955.
[I 2025-04-13 05:07:05,267] Trial 41 finished with value: 0.7690204222914503 and parameters: {'n_estimators': 172, 'max_depth': 18}. Best is trial 29 with value: 0.770889581169955.
[I 2025-04-13 05:07:07,140] Trial 42 finished with value: 0.7541709934233298 and parameters: {'n_estimators': 82, 'max_depth': 4}. Best is trial 29 with value: 0.770889581169955.
[I 2025-04-13 05:07:09,267] Trial 43 finished with value: 0.7615610938040844 and parameters: {'n_estimators': 158, 'max_depth': 8}. Best is trial 29 with value: 0.770889581169955.
[I 2025-04-13 05:07:11,652] Trial 44 finished with value: 0.7615610938040844 and parameters: {'n_estimators': 147, 'max_depth': 7}. Best is trial 29 with value: 0.770889581169955.
[I 2025-04-13 05:07:13,669] Trial 45 finished with value: 0.76711664935964 and parameters: {'n_estimators': 73, 'max_depth': 6}. Best is trial 29 with value: 0.770889581169955.
[I 2025-04-13 05:07:14,674] Trial 46 finished with value: 0.7670647282796814 and parameters: {'n_estimators': 65, 'max_depth': 13}. Best is trial 29 with value: 0.770889581169955.
[I 2025-04-13 05:07:15,923] Trial 47 finished with value: 0.7596746278989269 and parameters: {'n_estimators': 111, 'max_depth': 6}. Best is trial 29 with value: 0.770889581169955.
[I 2025-04-13 05:07:18,500] Trial 48 finished with value: 0.7522672204915196 and parameters: {'n_estimators': 199, 'max_depth': 4}. Best is trial 29 with value: 0.770889581169955.
[I 2025-04-13 05:07:20,668] Trial 49 finished with value: 0.7559709241952233 and parameters: {'n_estimators': 95, 'max_depth': 17}. Best is trial 29 with value: 0.770889581169955.

This code prints the best training accuracy and the corresponding hyperparameters from the Optuna study's best trial. It helps identify the optimal model configuration based on the highest accuracy achieved.

In [44]:
print(f'best traiing accuracy: {study.best_trial.value}')
print(f'best trail parameters: {study.best_trial.params}')

best traiing accuracy: 0.770889581169955
best trail parameters: {'n_estimators': 177, 'max_depth': 9}

This code trains a RandomForestClassifier using the best hyperparameters from the Optuna study, makes predictions on the test set, calculates the accuracy, and prints the test accuracy.

In [45]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.76

This code imports various Optuna visualization functions to analyze the optimization study results. These plots help in understanding the relationship between hyperparameters and the objective function, as well as identifying the most important parameters.

In [46]:
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_param_importances, plot_contour

In [48]:
plot_optimization_history(study).show()

In [50]:
plot_parallel_coordinate(study).show()

In [53]:
plot_contour(study).show()

In [54]:
plot_slice(study).show()

In [57]:
plot_param_importances(study).show()

In [62]:
from optuna.visualization import plot_intermediate_values

This code imports three classifiers: RandomForestClassifier for ensemble learning, GradientBoostingClassifier for sequential model building, and SVC for support vector machine-based classification. These models are commonly used for various classification tasks.

In [63]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

This code utilizes Optuna for hyperparameter optimization of machine learning models, including SVM, RandomForest, and GradientBoosting. The objective function dynamically tunes the hyperparameters of the selected classifier, and the best model is evaluated on the test set to achieve the highest accuracy.

In [70]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

This code creates an Optuna study to maximize the model's performance by optimizing hyperparameters. The optimization process is performed for 100 trials to find the best combination of hyperparameters for the selected model.

In [71]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2025-04-13 05:51:22,692] A new study created in memory with name: no-name-de032ac7-9be0-4adc-9311-dcc9e7813ac1
[I 2025-04-13 05:51:22,743] Trial 0 finished with value: 0.7094972067039106 and parameters: {'classifier': 'SVM', 'C': 11.70467721598936, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 0 with value: 0.7094972067039106.
[I 2025-04-13 05:51:22,822] Trial 1 finished with value: 0.696461824953445 and parameters: {'classifier': 'SVM', 'C': 42.75292025824411, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 0 with value: 0.7094972067039106.
[I 2025-04-13 05:51:23,988] Trial 2 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 258, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 2 with value: 0.7690875232774674.
[I 2025-04-13 05:51:26,397] Trial 3 finished with value: 0.7616387337057727 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 290, 'learning_rate': 0.012771596854811416, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 2 with value: 0.7690875232774674.
[I 2025-04-13 05:51:31,016] Trial 4 finished with value: 0.7392923649906891 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 233, 'learning_rate': 0.020903917612338035, 'max_depth': 16, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 2 with value: 0.7690875232774674.
[I 2025-04-13 05:51:31,055] Trial 5 finished with value: 0.7728119180633147 and parameters: {'classifier': 'SVM', 'C': 0.12551758598807067, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 5 with value: 0.7728119180633147.
[I 2025-04-13 05:51:32,371] Trial 6 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 262, 'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 5 with value: 0.7728119180633147.
[I 2025-04-13 05:51:37,723] Trial 7 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 299, 'learning_rate': 0.08340350024671661, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 5 with value: 0.7728119180633147.
[I 2025-04-13 05:51:37,752] Trial 8 finished with value: 0.7262569832402234 and parameters: {'classifier': 'SVM', 'C': 0.330799458285596, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 5 with value: 0.7728119180633147.
[I 2025-04-13 05:51:38,336] Trial 9 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 132, 'max_depth': 17, 'min_samples_split': 10, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-04-13 05:51:38,804] Trial 10 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 86, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-04-13 05:51:39,340] Trial 11 finished with value: 0.7821229050279329 and parameters: {'classifier': 'RandomForest', 'n_estimators': 120, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-04-13 05:51:39,885] Trial 12 finished with value: 0.7821229050279329 and parameters: {'classifier': 'RandomForest', 'n_estimators': 121, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-04-13 05:51:40,541] Trial 13 finished with value: 0.7821229050279329 and parameters: {'classifier': 'RandomForest', 'n_estimators': 150, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-04-13 05:51:40,811] Trial 14 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 52, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-04-13 05:51:41,780] Trial 15 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 192, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-04-13 05:51:42,303] Trial 16 finished with value: 0.7746741154562383 and parameters: {'classifier': 'RandomForest', 'n_estimators': 114, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-04-13 05:51:43,118] Trial 17 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 183, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-04-13 05:51:43,624] Trial 18 finished with value: 0.756052141527002 and parameters: {'classifier': 'RandomForest', 'n_estimators': 97, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-04-13 05:51:45,808] Trial 19 finished with value: 0.7579143389199254 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 156, 'learning_rate': 0.2926383083536822, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-04-13 05:51:46,306] Trial 20 finished with value: 0.7765363128491621 and parameters: {'classifier': 'RandomForest', 'n_estimators': 68, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-04-13 05:51:47,298] Trial 21 finished with value: 0.7783985102420856 and parameters: {'classifier': 'RandomForest', 'n_estimators': 142, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-04-13 05:51:48,039] Trial 22 finished with value: 0.7802607076350093 and parameters: {'classifier': 'RandomForest', 'n_estimators': 167, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-04-13 05:51:48,557] Trial 23 finished with value: 0.7821229050279329 and parameters: {'classifier': 'RandomForest', 'n_estimators': 113, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-04-13 05:51:49,347] Trial 24 finished with value: 0.7448789571694601 and parameters: {'classifier': 'RandomForest', 'n_estimators': 202, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-04-13 05:51:49,884] Trial 25 finished with value: 0.7821229050279329 and parameters: {'classifier': 'RandomForest', 'n_estimators': 123, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-04-13 05:51:50,690] Trial 26 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 153, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-04-13 05:51:51,133] Trial 27 finished with value: 0.7839851024208566 and parameters: {'classifier': 'RandomForest', 'n_estimators': 92, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 27 with value: 0.7839851024208566.
[I 2025-04-13 05:51:52,379] Trial 28 finished with value: 0.7430167597765364 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 95, 'learning_rate': 0.0801721818785304, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 8}. Best is trial 27 with value: 0.7839851024208566.
[I 2025-04-13 05:51:52,418] Trial 29 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 1.613675455029247, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7858472998137801.
[I 2025-04-13 05:51:52,457] Trial 30 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.5076827479119868, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7858472998137801.
[I 2025-04-13 05:51:52,495] Trial 31 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.495084793344052, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7858472998137801.
[I 2025-04-13 05:51:52,534] Trial 32 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.4638728715957985, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7858472998137801.
[I 2025-04-13 05:51:52,574] Trial 33 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 1.80574436934853, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7858472998137801.
[I 2025-04-13 05:51:52,620] Trial 34 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.980972325769927, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7858472998137801.
[I 2025-04-13 05:51:52,663] Trial 35 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 6.364107028692216, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 29 with value: 0.7858472998137801.
[I 2025-04-13 05:51:52,710] Trial 36 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.9777974623489727, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7858472998137801.
[I 2025-04-13 05:51:52,757] Trial 37 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.229273974513659, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7858472998137801.
[I 2025-04-13 05:51:52,793] Trial 38 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8629521608436082, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:51:52,830] Trial 39 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.48996874321497497, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:51:52,871] Trial 40 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.259064918430327, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:51:52,924] Trial 41 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.927012204820131, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:51:52,962] Trial 42 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.7933343775564254, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:51:52,997] Trial 43 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5202082814164015, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:51:53,033] Trial 44 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.7688835689261133, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:51:53,070] Trial 45 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.7236779881963771, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:51:53,110] Trial 46 finished with value: 0.7690875232774674 and parameters: {'classifier': 'SVM', 'C': 0.7630825260756949, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:51:53,164] Trial 47 finished with value: 0.7616387337057727 and parameters: {'classifier': 'SVM', 'C': 0.2369469078726621, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:51:53,206] Trial 48 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6567835211197589, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:51:53,248] Trial 49 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6780874723894701, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:51:53,282] Trial 50 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2154666314600045, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:51:53,321] Trial 51 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6688328395225799, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:51:53,359] Trial 52 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8618188265063951, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:51:53,393] Trial 53 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.3865007954059414, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:51:54,892] Trial 54 finished with value: 0.6852886405959032 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 226, 'learning_rate': 0.2726528635433392, 'max_depth': 20, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:51:54,929] Trial 55 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.9320420754372688, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:51:54,964] Trial 56 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5970661310192893, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:51:55,004] Trial 57 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.30381839569335767, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:51:55,047] Trial 58 finished with value: 0.7541899441340782 and parameters: {'classifier': 'SVM', 'C': 0.9302675204176132, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:52:00,836] Trial 59 finished with value: 0.7430167597765363 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 270, 'learning_rate': 0.039390041107301745, 'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:52:00,873] Trial 60 finished with value: 0.7374301675977654 and parameters: {'classifier': 'SVM', 'C': 0.4490439753708625, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:52:00,907] Trial 61 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2326972822667068, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 38 with value: 0.7858472998137803.
[I 2025-04-13 05:52:00,942] Trial 62 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15068887109277518, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-04-13 05:52:00,976] Trial 63 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.18143053462391648, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-04-13 05:52:01,009] Trial 64 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10013409915851987, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-04-13 05:52:01,046] Trial 65 finished with value: 0.7113594040968342 and parameters: {'classifier': 'SVM', 'C': 0.12969613026309412, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-04-13 05:52:01,081] Trial 66 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1144545199244533, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-04-13 05:52:01,121] Trial 67 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10775224349520589, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-04-13 05:52:04,537] Trial 68 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 223, 'learning_rate': 0.1449808739493571, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 2}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-04-13 05:52:04,586] Trial 69 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 0.11835316858775398, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-04-13 05:52:04,630] Trial 70 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16141385859953328, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-04-13 05:52:04,666] Trial 71 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.15997641265805929, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-04-13 05:52:04,698] Trial 72 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16370740183522203, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-04-13 05:52:04,731] Trial 73 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1006350091817886, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-04-13 05:52:04,764] Trial 74 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17309226607234232, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-04-13 05:52:04,797] Trial 75 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.15558528115873965, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-04-13 05:52:04,861] Trial 76 finished with value: 0.702048417132216 and parameters: {'classifier': 'SVM', 'C': 25.053727403662535, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-04-13 05:52:04,897] Trial 77 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1642465648554147, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-04-13 05:52:04,931] Trial 78 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1030077395459936, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-04-13 05:52:04,974] Trial 79 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17944469640240845, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.

This code prints the accuracy of the best trial found during the optimization process and displays the hyperparameters associated with that trial. The best trial represents the optimal combination of hyperparameters for the selected model.

In [72]:
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best trial parameters: {study.best_trial.params}')

Best trial accuracy: 0.7895716945996275
Best trial parameters: {'classifier': 'SVM', 'C': 0.15068887109277518, 'kernel': 'linear', 'gamma': 'auto'}

The study.trials_dataframe() method in Optuna converts the trial results of the study into a pandas DataFrame. This DataFrame contains details about each trial, including the trial number, hyperparameters, objective values (e.g., accuracy), and other relevant metrics, making it easier to analyze and visualize the optimization process.

In [74]:
study.trials_dataframe()

    number     value  ... params_n_estimators     state
0        0  0.709497  ...                 NaN  COMPLETE
1        1  0.696462  ...                 NaN  COMPLETE
2        2  0.769088  ...               258.0  COMPLETE
3        3  0.761639  ...               290.0  COMPLETE
4        4  0.739292  ...               233.0  COMPLETE
..     ...       ...  ...                 ...       ...
95      95  0.785847  ...                 NaN  COMPLETE
96      96  0.785847  ...                 NaN  COMPLETE
97      97  0.776536  ...                 NaN  COMPLETE
98      98  0.789572  ...                 NaN  COMPLETE
99      99  0.783985  ...                 NaN  COMPLETE

[100 rows x 16 columns]

The code study.trials_dataframe()['params_classifier'].value_counts() counts the occurrences of each classifier type used during the trials in the Optuna study. It shows how many times each classifier (e.g., 'SVM', 'RandomForest', 'GradientBoosting') was selected during the hyperparameter optimization process.

In [75]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 71
RandomForest        20
GradientBoosting     9
Name: count, dtype: int64

The code study.trials_dataframe().groupby('params_classifier')['value'].mean() groups the trials by the classifier type (e.g., 'SVM', 'RandomForest', 'GradientBoosting') and calculates the mean objective value (such as accuracy) for each classifier. This allows you to compare the average performance of each model across all trials in the study.

In [76]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.741155
RandomForest        0.771974
SVM                 0.777874
Name: value, dtype: float64